module FFMPEG::PixelFormat
  inline :C do |builder|
    FFMPEG.builder_defaults builder

    PIXEL_FORMAT_CONSTANTS = [
      'PIX_FMT_ABGR',
      'PIX_FMT_ARGB',
      'PIX_FMT_BGR24',
      'PIX_FMT_BGR32',
      'PIX_FMT_BGR32_1',
      'PIX_FMT_BGR4',
      'PIX_FMT_BGR4_BYTE',
      'PIX_FMT_BGR555',
      'PIX_FMT_BGR555BE',
      'PIX_FMT_BGR555LE',
      'PIX_FMT_BGR565',
      'PIX_FMT_BGR565BE',
      'PIX_FMT_BGR565LE',
      'PIX_FMT_BGR8',
      'PIX_FMT_BGRA',
      'PIX_FMT_GRAY16',
      'PIX_FMT_GRAY16BE',
      'PIX_FMT_GRAY16LE',
      'PIX_FMT_GRAY8',
      'PIX_FMT_MONOBLACK',
      'PIX_FMT_MONOWHITE',
      'PIX_FMT_NONE',
      'PIX_FMT_NV12',
      'PIX_FMT_NV21',
      'PIX_FMT_PAL8',
      'PIX_FMT_RGB24',
      'PIX_FMT_RGB32',
      'PIX_FMT_RGB32_1',
      'PIX_FMT_RGB4',
      'PIX_FMT_RGB48',
      'PIX_FMT_RGB48BE',
      'PIX_FMT_RGB48LE',
      'PIX_FMT_RGB4_BYTE',
      'PIX_FMT_RGB555',
      'PIX_FMT_RGB555BE',
      'PIX_FMT_RGB555LE',
      'PIX_FMT_RGB565',
      'PIX_FMT_RGB565BE',
      'PIX_FMT_RGB565LE',
      'PIX_FMT_RGB8',
      'PIX_FMT_RGBA',
      'PIX_FMT_UYVY422',
      'PIX_FMT_UYYVYY411',
      'PIX_FMT_VAAPI_IDCT',
      'PIX_FMT_VAAPI_MOCO',
      'PIX_FMT_VAAPI_VLD',
      'PIX_FMT_VDPAU_H264',
      'PIX_FMT_VDPAU_MPEG1',
      'PIX_FMT_VDPAU_MPEG2',
      'PIX_FMT_VDPAU_VC1',
      'PIX_FMT_VDPAU_WMV3',
      'PIX_FMT_XVMC_MPEG2_IDCT',
      'PIX_FMT_XVMC_MPEG2_MC',
      'PIX_FMT_YUV410P',
      'PIX_FMT_YUV411P',
      'PIX_FMT_YUV420P',
      'PIX_FMT_YUV420P16',
      'PIX_FMT_YUV420PBE',
      'PIX_FMT_YUV420PLE',
      'PIX_FMT_YUV422P',
      'PIX_FMT_YUV422P16',
      'PIX_FMT_YUV422PBE',
      'PIX_FMT_YUV422PLE',
      'PIX_FMT_YUV440P',
      'PIX_FMT_YUV444P',
      'PIX_FMT_YUV444P16',
      'PIX_FMT_YUV444PBE',
      'PIX_FMT_YUV444PLE',
      'PIX_FMT_YUVA420P',
      'PIX_FMT_YUVJ420P',
      'PIX_FMT_YUVJ422P',
      'PIX_FMT_YUVJ440P',
      'PIX_FMT_YUVJ444P',
      'PIX_FMT_YUYV422',
    ]

    PIXEL_FORMAT_CONSTANTS.each do |const|
      builder.map_c_const const => ['int', const.sub(/PIX_FMT_/, '')]
    end
  end
end

